# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "~/repos/devops-data-science/data/models")
v <- vetiver_pin_read(b, "penguin_model")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
